name: "typedoc"

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Update npm
        # Install the latest version of npm since we need npm 11.5.1 or later to publish to npm using OIDC (see
        # https://docs.npmjs.com/trusted-publishers).
        run: npm install -g npm@latest

      - name: Install bun
        run: npm install -g bun

      - name: Install packages
        run: bun install

      - name: Generate documentation
        run: bun run build-docs

      - name: Upload generated documentation to Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./docs

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
